[tool.yapf]
align_closing_bracket_with_visual_indent = false
based_on_style = "google"
blank_line_before_nested_class_or_def = true
blank_lines_between_top_level_imports_and_variables = 2
coalesce_brackets = true
column_limit = 96
continuation_indent_width = 4
dedent_closing_brackets = false
force_multiline_dict = true
indent_closing_brackets = false
indent_width = 4
spaces_before_comment = 4
split_before_first_argument = false
split_before_logical_operator = true
split_complex_comprehension = true

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_any_unimported = true
warn_return_any = true
warn_unused_ignores = true
no_implicit_optional = true
show_error_codes = true
